export const countries = {
  AF: 'Afghanistan',
  AX: 'Aland Islands',
  AL: 'Albania',
  DZ: 'Algeria',
  AS: 'American Samoa',
  AD: 'Andorra',
  AO: 'Angola',
  AI: 'Anguilla',
  AQ: 'Antarctica',
  AG: 'Antigua And Barbuda',
  AR: 'Argentina',
  AM: 'Armenia',
  AW: 'Aruba',
  AU: 'Australia',
  AT: 'Austria',
  AZ: 'Azerbaijan',
  BS: 'Bahamas',
  BH: 'Bahrain',
  BD: 'Bangladesh',
  BB: 'Barbados',
  BY: 'Belarus',
  BE: 'Belgium',
  BZ: 'Belize',
  BJ: 'Benin',
  BM: 'Bermuda',
  BT: 'Bhutan',
  BO: 'Bolivia',
  BA: 'Bosnia And Herzegovina',
  BW: 'Botswana',
  BV: 'Bouvet Island',
  BR: 'Brazil',
  IO: 'British Indian Ocean Territory',
  BN: 'Brunei Darussalam',
  BG: 'Bulgaria',
  BF: 'Burkina Faso',
  BI: 'Burundi',
  KH: 'Cambodia',
  CM: 'Cameroon',
  CA: 'Canada',
  CV: 'Cape Verde',
  KY: 'Cayman Islands',
  CF: 'Central African Republic',
  TD: 'Chad',
  CL: 'Chile',
  CN: 'China',
  CX: 'Christmas Island',
  CC: 'Cocos (Keeling) Islands',
  CO: 'Colombia',
  KM: 'Comoros',
  CG: 'Congo',
  CD: 'Congo, Democratic Republic',
  CK: 'Cook Islands',
  CR: 'Costa Rica',
  CI: 'Cote D\'Ivoire',
  HR: 'Croatia',
  CU: 'Cuba',
  CY: 'Cyprus',
  CZ: 'Czech Republic',
  DK: 'Denmark',
  DJ: 'Djibouti',
  DM: 'Dominica',
  DO: 'Dominican Republic',
  EC: 'Ecuador',
  EG: 'Egypt',
  SV: 'El Salvador',
  GQ: 'Equatorial Guinea',
  ER: 'Eritrea',
  EE: 'Estonia',
  ET: 'Ethiopia',
  FK: 'Falkland Islands (Malvinas)',
  FO: 'Faroe Islands',
  FJ: 'Fiji',
  FI: 'Finland',
  FR: 'France',
  GF: 'French Guiana',
  PF: 'French Polynesia',
  TF: 'French Southern Territories',
  GA: 'Gabon',
  GM: 'Gambia',
  GE: 'Georgia',
  DE: 'Germany',
  GH: 'Ghana',
  GI: 'Gibraltar',
  GR: 'Greece',
  GL: 'Greenland',
  GD: 'Grenada',
  GP: 'Guadeloupe',
  GU: 'Guam',
  GT: 'Guatemala',
  GG: 'Guernsey',
  GN: 'Guinea',
  GW: 'Guinea-Bissau',
  GY: 'Guyana',
  HT: 'Haiti',
  HM: 'Heard Island & Mcdonald Islands',
  VA: 'Holy See (Vatican City State)',
  HN: 'Honduras',
  HK: 'Hong Kong',
  HU: 'Hungary',
  IS: 'Iceland',
  IN: 'India',
  ID: 'Indonesia',
  IR: 'Iran, Islamic Republic Of',
  IQ: 'Iraq',
  IE: 'Ireland',
  IM: 'Isle Of Man',
  IL: 'Israel',
  IT: 'Italy',
  JM: 'Jamaica',
  JP: 'Japan',
  JE: 'Jersey',
  JO: 'Jordan',
  KZ: 'Kazakhstan',
  KE: 'Kenya',
  KI: 'Kiribati',
  KR: 'Korea',
  KW: 'Kuwait',
  KG: 'Kyrgyzstan',
  LA: 'Lao People\'s Democratic Republic',
  LV: 'Latvia',
  LB: 'Lebanon',
  LS: 'Lesotho',
  LR: 'Liberia',
  LY: 'Libyan Arab Jamahiriya',
  LI: 'Liechtenstein',
  LT: 'Lithuania',
  LU: 'Luxembourg',
  MO: 'Macao',
  MK: 'Macedonia',
  MG: 'Madagascar',
  MW: 'Malawi',
  MY: 'Malaysia',
  MV: 'Maldives',
  ML: 'Mali',
  MT: 'Malta',
  MH: 'Marshall Islands',
  MQ: 'Martinique',
  MR: 'Mauritania',
  MU: 'Mauritius',
  YT: 'Mayotte',
  MX: 'Mexico',
  FM: 'Micronesia, Federated States Of',
  MD: 'Moldova',
  MC: 'Monaco',
  MN: 'Mongolia',
  ME: 'Montenegro',
  MS: 'Montserrat',
  MA: 'Morocco',
  MZ: 'Mozambique',
  MM: 'Myanmar',
  NA: 'Namibia',
  NR: 'Nauru',
  NP: 'Nepal',
  NL: 'Netherlands',
  AN: 'Netherlands Antilles',
  NC: 'New Caledonia',
  NZ: 'New Zealand',
  NI: 'Nicaragua',
  NE: 'Niger',
  NG: 'Nigeria',
  NU: 'Niue',
  NF: 'Norfolk Island',
  MP: 'Northern Mariana Islands',
  NO: 'Norway',
  OM: 'Oman',
  PK: 'Pakistan',
  PW: 'Palau',
  PS: 'Palestinian Territory, Occupied',
  PA: 'Panama',
  PG: 'Papua New Guinea',
  PY: 'Paraguay',
  PE: 'Peru',
  PH: 'Philippines',
  PN: 'Pitcairn',
  PL: 'Poland',
  PT: 'Portugal',
  PR: 'Puerto Rico',
  QA: 'Qatar',
  RE: 'Reunion',
  RO: 'Romania',
  RU: 'Russian Federation',
  RW: 'Rwanda',
  BL: 'Saint Barthelemy',
  SH: 'Saint Helena',
  KN: 'Saint Kitts And Nevis',
  LC: 'Saint Lucia',
  MF: 'Saint Martin',
  PM: 'Saint Pierre And Miquelon',
  VC: 'Saint Vincent And Grenadines',
  WS: 'Samoa',
  SM: 'San Marino',
  ST: 'Sao Tome And Principe',
  SA: 'Saudi Arabia',
  SN: 'Senegal',
  RS: 'Serbia',
  SC: 'Seychelles',
  SL: 'Sierra Leone',
  SG: 'Singapore',
  SK: 'Slovakia',
  SI: 'Slovenia',
  SB: 'Solomon Islands',
  SO: 'Somalia',
  ZA: 'South Africa',
  GS: 'South Georgia And Sandwich Isl.',
  ES: 'Spain',
  LK: 'Sri Lanka',
  SD: 'Sudan',
  SR: 'Suriname',
  SJ: 'Svalbard And Jan Mayen',
  SZ: 'Swaziland',
  SE: 'Sweden',
  CH: 'Switzerland',
  SY: 'Syrian Arab Republic',
  TW: 'Taiwan',
  TJ: 'Tajikistan',
  TZ: 'Tanzania',
  TH: 'Thailand',
  TL: 'Timor-Leste',
  TG: 'Togo',
  TK: 'Tokelau',
  TO: 'Tonga',
  TT: 'Trinidad And Tobago',
  TN: 'Tunisia',
  TR: 'Turkey',
  TM: 'Turkmenistan',
  TC: 'Turks And Caicos Islands',
  TV: 'Tuvalu',
  UG: 'Uganda',
  UA: 'Ukraine',
  AE: 'United Arab Emirates',
  GB: 'United Kingdom',
  US: 'United States',
  UM: 'United States Outlying Islands',
  UY: 'Uruguay',
  UZ: 'Uzbekistan',
  VU: 'Vanuatu',
  VE: 'Venezuela',
  VN: 'Viet Nam',
  VG: 'Virgin Islands, British',
  VI: 'Virgin Islands, U.S.',
  WF: 'Wallis And Futuna',
  EH: 'Western Sahara',
  YE: 'Yemen',
  ZM: 'Zambia',
  ZW: 'Zimbabwe'
}

export const countriesCodes = {
  ["Afghanistan"]:'AF',["Aland Islands"]:'AX',["Albania"]:'AL',["Algeria"]:'DZ',["American Samoa"]:'AS',["Andorra"]:'AD',["Angola"]:'AO',["Anguilla"]:'AI',["Antarctica"]:'AQ',["Antigua And Barbuda"]:'AG',["Argentina"]:'AR',["Armenia"]:'AM',["Aruba"]:'AW',["Australia"]:'AU',["Austria"]:'AT',["Azerbaijan"]:'AZ',["Bahamas"]:'BS',["Bahrain"]:'BH',["Bangladesh"]:'BD',["Barbados"]:'BB',["Belarus"]:'BY',["Belgium"]:'BE',["Belize"]:'BZ',["Benin"]:'BJ',["Bermuda"]:'BM',["Bhutan"]:'BT',["Bolivia"]:'BO',["Bosnia And Herzegovina"]:'BA',["Botswana"]:'BW',["Bouvet Island"]:'BV',["Brazil"]:'BR',["British Indian Ocean Territory"]:'IO',["Brunei Darussalam"]:'BN',["Bulgaria"]:'BG',["Burkina Faso"]:'BF',["Burundi"]:'BI',["Cambodia"]:'KH',["Cameroon"]:'CM',["Canada"]:'CA',["Cape Verde"]:'CV',["Cayman Islands"]:'KY',["Central African Republic"]:'CF',["Chad"]:'TD',["Chile"]:'CL',["China"]:'CN',["Christmas Island"]:'CX',["Cocos (Keeling) Islands"]:'CC',["Colombia"]:'CO',["Comoros"]:'KM',["Congo"]:'CG',["Congo, Democratic Republic"]:'CD',["Cook Islands"]:'CK',["Costa Rica"]:'CR',["Cote D'Ivoire"]:'CI',["Croatia"]:'HR',["Cuba"]:'CU',["Cyprus"]:'CY',["Czech Republic"]:'CZ',["Denmark"]:'DK',["Djibouti"]:'DJ',["Dominica"]:'DM',["Dominican Republic"]:'DO',["Ecuador"]:'EC',["Egypt"]:'EG',["El Salvador"]:'SV',["Equatorial Guinea"]:'GQ',["Eritrea"]:'ER',["Estonia"]:'EE',["Ethiopia"]:'ET',["Falkland Islands (Malvinas)"]:'FK',["Faroe Islands"]:'FO',["Fiji"]:'FJ',["Finland"]:'FI',["France"]:'FR',["French Guiana"]:'GF',["French Polynesia"]:'PF',["French Southern Territories"]:'TF',["Gabon"]:'GA',["Gambia"]:'GM',["Georgia"]:'GE',["Germany"]:'DE',["Ghana"]:'GH',["Gibraltar"]:'GI',["Greece"]:'GR',["Greenland"]:'GL',["Grenada"]:'GD',["Guadeloupe"]:'GP',["Guam"]:'GU',["Guatemala"]:'GT',["Guernsey"]:'GG',["Guinea"]:'GN',["Guinea-Bissau"]:'GW',["Guyana"]:'GY',["Haiti"]:'HT',["Heard Island & Mcdonald Islands"]:'HM',["Holy See (Vatican City State)"]:'VA',["Honduras"]:'HN',["Hong Kong"]:'HK',["Hungary"]:'HU',["Iceland"]:'IS',["India"]:'IN',["Indonesia"]:'ID',["Iran, Islamic Republic Of"]:'IR',["Iraq"]:'IQ',["Ireland"]:'IE',["Isle Of Man"]:'IM',["Israel"]:'IL',["Italy"]:'IT',["Jamaica"]:'JM',["Japan"]:'JP',["Jersey"]:'JE',["Jordan"]:'JO',["Kazakhstan"]:'KZ',["Kenya"]:'KE',["Kiribati"]:'KI',["Korea"]:'KR',["Kuwait"]:'KW',["Kyrgyzstan"]:'KG',["Lao People's Democratic Republic"]:'LA',["Latvia"]:'LV',["Lebanon"]:'LB',["Lesotho"]:'LS',["Liberia"]:'LR',["Libyan Arab Jamahiriya"]:'LY',["Liechtenstein"]:'LI',["Lithuania"]:'LT',["Luxembourg"]:'LU',["Macao"]:'MO',["Macedonia"]:'MK',["Madagascar"]:'MG',["Malawi"]:'MW',["Malaysia"]:'MY',["Maldives"]:'MV',["Mali"]:'ML',["Malta"]:'MT',["Marshall Islands"]:'MH',["Martinique"]:'MQ',["Mauritania"]:'MR',["Mauritius"]:'MU',["Mayotte"]:'YT',["Mexico"]:'MX',["Micronesia, Federated States Of"]:'FM',["Moldova"]:'MD',["Monaco"]:'MC',["Mongolia"]:'MN',["Montenegro"]:'ME',["Montserrat"]:'MS',["Morocco"]:'MA',["Mozambique"]:'MZ',["Myanmar"]:'MM',["Namibia"]:'NA',["Nauru"]:'NR',["Nepal"]:'NP',["Netherlands"]:'NL',["Netherlands Antilles"]:'AN',["New Caledonia"]:'NC',["New Zealand"]:'NZ',["Nicaragua"]:'NI',["Niger"]:'NE',["Nigeria"]:'NG',["Niue"]:'NU',["Norfolk Island"]:'NF',["Northern Mariana Islands"]:'MP',["Norway"]:'NO',["Oman"]:'OM',["Pakistan"]:'PK',["Palau"]:'PW',["Palestinian Territory, Occupied"]:'PS',["Panama"]:'PA',["Papua New Guinea"]:'PG',["Paraguay"]:'PY',["Peru"]:'PE',["Philippines"]:'PH',["Pitcairn"]:'PN',["Poland"]:'PL',["Portugal"]:'PT',["Puerto Rico"]:'PR',["Qatar"]:'QA',["Reunion"]:'RE',["Romania"]:'RO',["Russian Federation"]:'RU',["Rwanda"]:'RW',["Saint Barthelemy"]:'BL',["Saint Helena"]:'SH',["Saint Kitts And Nevis"]:'KN',["Saint Lucia"]:'LC',["Saint Martin"]:'MF',["Saint Pierre And Miquelon"]:'PM',["Saint Vincent And Grenadines"]:'VC',["Samoa"]:'WS',["San Marino"]:'SM',["Sao Tome And Principe"]:'ST',["Saudi Arabia"]:'SA',["Senegal"]:'SN',["Serbia"]:'RS',["Seychelles"]:'SC',["Sierra Leone"]:'SL',["Singapore"]:'SG',["Slovakia"]:'SK',["Slovenia"]:'SI',["Solomon Islands"]:'SB',["Somalia"]:'SO',["South Africa"]:'ZA',["South Georgia And Sandwich Isl."]:'GS',["Spain"]:'ES',["Sri Lanka"]:'LK',["Sudan"]:'SD',["Suriname"]:'SR',["Svalbard And Jan Mayen"]:'SJ',["Swaziland"]:'SZ',["Sweden"]:'SE',["Switzerland"]:'CH',["Syrian Arab Republic"]:'SY',["Taiwan"]:'TW',["Tajikistan"]:'TJ',["Tanzania"]:'TZ',["Thailand"]:'TH',["Timor-Leste"]:'TL',["Togo"]:'TG',["Tokelau"]:'TK',["Tonga"]:'TO',["Trinidad And Tobago"]:'TT',["Tunisia"]:'TN',["Turkey"]:'TR',["Turkmenistan"]:'TM',["Turks And Caicos Islands"]:'TC',["Tuvalu"]:'TV',["Uganda"]:'UG',["Ukraine"]:'UA',["United Arab Emirates"]:'AE',["United Kingdom"]:'GB',["United States"]:'US',["United States Outlying Islands"]:'UM',["Uruguay"]:'UY',["Uzbekistan"]:'UZ',["Vanuatu"]:'VU',["Venezuela"]:'VE',["Viet Nam"]:'VN',["Virgin Islands, British"]:'VG',["Virgin Islands, U.S."]:'VI',["Wallis And Futuna"]:'WF',["Western Sahara"]:'EH',["Yemen"]:'YE',["Zambia"]:'ZM',["Zimbabwe"]:'ZW'
}

export const callingCodes = {
  ["+7 840"]:'Abkhazia',["+93"]:'Afghanistan',["+355"]:'Albania',["+213"]:'Algeria',["+1 684"]:'American Samoa',["+376"]:'Andorra',["+244"]:'Angola',["+1 264"]:'Anguilla',["+1 268"]:'Antigua and Barbuda',["+54"]:'Argentina',["+374"]:'Armenia',["+297"]:'Aruba',["+247"]:'Ascension',["+61"]:'Australia',["+672"]:'Australian External Territories',["+43"]:'Austria',["+994"]:'Azerbaijan',["+1 242"]:'Bahamas',["+973"]:'Bahrain',["+880"]:'Bangladesh',["+1 246"]:'Barbados',["+1 268"]:'Barbuda',["+375"]:'Belarus',["+32"]:'Belgium',["+501"]:'Belize',["+229"]:'Benin',["+1 441"]:'Bermuda',["+975"]:'Bhutan',["+591"]:'Bolivia',["+387"]:'Bosnia and Herzegovina',["+267"]:'Botswana',["+55"]:'Brazil',["+246"]:'British Indian Ocean Territory',["+1 284"]:'British Virgin Islands',["+673"]:'Brunei',["+359"]:'Bulgaria',["+226"]:'Burkina Faso',["+257"]:'Burundi',["+855"]:'Cambodia',["+237"]:'Cameroon',["+1"]:'Canada',["+238"]:'Cape Verde',["+ 345"]:'Cayman Islands',["+236"]:'Central African Republic',["+235"]:'Chad',["+56"]:'Chile',["+86"]:'China',["+61"]:'Christmas Island',["+61"]:'Cocos-Keeling Islands',["+57"]:'Colombia',["+269"]:'Comoros',["+242"]:'Congo',["+243"]:'Congo, Dem. Rep. of (Zaire)',["+682"]:'Cook Islands',["+506"]:'Costa Rica',["+385"]:'Croatia',["+53"]:'Cuba',["+599"]:'Curacao',["+537"]:'Cyprus',["+420"]:'Czech Republic',["+45"]:'Denmark',["+246"]:'Diego Garcia',["+253"]:'Djibouti',["+1 767"]:'Dominica',["+1 809"]:'Dominican Republic',["+670"]:'East Timor',["+56"]:'Easter Island',["+593"]:'Ecuador',["+20"]:'Egypt',["+503"]:'El Salvador',["+240"]:'Equatorial Guinea',["+291"]:'Eritrea',["+372"]:'Estonia',["+251"]:'Ethiopia',["+500"]:'Falkland Islands',["+298"]:'Faroe Islands',["+679"]:'Fiji',["+358"]:'Finland',["+33"]:'France',["+596"]:'French Antilles',["+594"]:'French Guiana',["+689"]:'French Polynesia',["+241"]:'Gabon',["+220"]:'Gambia',["+995"]:'Georgia',["+49"]:'Germany',["+233"]:'Ghana',["+350"]:'Gibraltar',["+30"]:'Greece',["+299"]:'Greenland',["+1 473"]:'Grenada',["+590"]:'Guadeloupe',["+1 671"]:'Guam',["+502"]:'Guatemala',["+224"]:'Guinea',["+245"]:'Guinea-Bissau',["+595"]:'Guyana',["+509"]:'Haiti',["+504"]:'Honduras',["+852"]:'Hong Kong SAR China',["+36"]:'Hungary',["+354"]:'Iceland',["+91"]:'India',["+62"]:'Indonesia',["+98"]:'Iran',["+964"]:'Iraq',["+353"]:'Ireland',["+972"]:'Israel',["+39"]:'Italy',["+225"]:'Ivory Coast',["+1 876"]:'Jamaica',["+81"]:'Japan',["+962"]:'Jordan',["+7 7"]:'Kazakhstan',["+254"]:'Kenya',["+686"]:'Kiribati',["+965"]:'Kuwait',["+996"]:'Kyrgyzstan',["+856"]:'Laos',["+371"]:'Latvia',["+961"]:'Lebanon',["+266"]:'Lesotho',["+231"]:'Liberia',["+218"]:'Libya',["+423"]:'Liechtenstein',["+370"]:'Lithuania',["+352"]:'Luxembourg',["+853"]:'Macau SAR China',["+389"]:'Macedonia',["+261"]:'Madagascar',["+265"]:'Malawi',["+60"]:'Malaysia',["+960"]:'Maldives',["+223"]:'Mali',["+356"]:'Malta',["+692"]:'Marshall Islands',["+596"]:'Martinique',["+222"]:'Mauritania',["+230"]:'Mauritius',["+262"]:'Mayotte',["+52"]:'Mexico',["+691"]:'Micronesia',["+1 808"]:'Midway Island',["+373"]:'Moldova',["+377"]:'Monaco',["+976"]:'Mongolia',["+382"]:'Montenegro',["+1664"]:'Montserrat',["+212"]:'Morocco',["+95"]:'Myanmar',["+264"]:'Namibia',["+674"]:'Nauru',["+977"]:'Nepal',["+31"]:'Netherlands',["+599"]:'Netherlands Antilles',["+1 869"]:'Nevis',["+687"]:'New Caledonia',["+64"]:'New Zealand',["+505"]:'Nicaragua',["+227"]:'Niger',["+234"]:'Nigeria',["+683"]:'Niue',["+672"]:'Norfolk Island',["+850"]:'North Korea',["+1 670"]:'Northern Mariana Islands',["+47"]:'Norway',["+968"]:'Oman',["+92"]:'Pakistan',["+680"]:'Palau',["+970"]:'Palestinian Territory',["+507"]:'Panama',["+675"]:'Papua New Guinea',["+595"]:'Paraguay',["+51"]:'Peru',["+63"]:'Philippines',["+48"]:'Poland',["+351"]:'Portugal',["+1 787"]:'Puerto Rico',["+974"]:'Qatar',["+262"]:'Reunion',["+40"]:'Romania',["+7"]:'Russia',["+250"]:'Rwanda',["+685"]:'Samoa',["+378"]:'San Marino',["+966"]:'Saudi Arabia',["+221"]:'Senegal',["+381"]:'Serbia',["+248"]:'Seychelles',["+232"]:'Sierra Leone',["+65"]:'Singapore',["+421"]:'Slovakia',["+386"]:'Slovenia',["+677"]:'Solomon Islands',["+27"]:'South Africa',["+500"]:'South Georgia and the South Sandwich Islands',["+82"]:'South Korea',["+34"]:'Spain',["+94"]:'Sri Lanka',["+249"]:'Sudan',["+597"]:'Suriname',["+268"]:'Swaziland',["+46"]:'Sweden',["+41"]:'Switzerland',["+963"]:'Syria',["+886"]:'Taiwan',["+992"]:'Tajikistan',["+255"]:'Tanzania',["+66"]:'Thailand',["+670"]:'Timor Leste',["+228"]:'Togo',["+690"]:'Tokelau',["+676"]:'Tonga',["+1 868"]:'Trinidad and Tobago',["+216"]:'Tunisia',["+90"]:'Turkey',["+993"]:'Turkmenistan',["+1 649"]:'Turks and Caicos Islands',["+688"]:'Tuvalu',["+1 340"]:'U.S. Virgin Islands',["+256"]:'Uganda',["+380"]:'Ukraine',["+971"]:'United Arab Emirates',["+44"]:'United Kingdom',["+1"]:'United States',["+598"]:'Uruguay',["+998"]:'Uzbekistan',["+678"]:'Vanuatu',["+58"]:'Venezuela',["+84"]:'Vietnam',["+1 808"]:'Wake Island',["+681"]:'Wallis and Futuna',["+967"]:'Yemen',["+260"]:'Zambia',["+255"]:'Zanzibar',["+263"]:'Zimbabwe'
}