export const userConstants = {
    REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',

    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',
    HIDE_FAILURE_MESSAGE: 'HIDE_FAILURE_MESSAGE',
    
    LOGOUT: 'USERS_LOGOUT',

    CHECK_EMAIL_REQUEST: 'USERS_EMAIL_CHECK_REQUEST',
    CHECK_EMAIL_SUCCESS: 'USERS_EMAIL_CHECK_SUCCESS',
    CHECK_EMAIL_FAILURE: 'USERS_EMAIL_CHECK_FAILURE',

    CHECK_MOBILE_REQUEST: 'USERS_MOBILE_CHECK_REQUEST',
    CHECK_MOBILE_SUCCESS: 'USERS_MOBILE_CHECK_SUCCESS',
    CHECK_MOBILE_FAILURE: 'USERS_MOBILE_CHECK_FAILURE',

    OTP_MOBILE_REQUEST: 'OTP_MOBILE_SENT_REQUEST',
    OTP_MOBILE_SUCCESS: 'OTP_MOBILE_SENT_SUCCESS',
    OTP_MOBILE_FAILURE: 'OTP_MOBILE_SENT_FAILURE',
    OTP_MOBILE_CLEAN_ERROR: 'OTP_MOBILE_CLEAN_ERROR',

    OTP_EMAIL_REQUEST: 'OTP_EMAIL_SENT_REQUEST',
    OTP_EMAIL_SUCCESS: 'OTP_EMAIL_SENT_SUCCESS',
    OTP_EMAIL_ALERT_DISMISS: 'OTP_EMAIL_ALERT_DISMISS',
    OTP_EMAIL_FAILURE: 'OTP_EMAIL_SENT_FAILURE',

    OTP_VALIDATION_REQUEST: 'OTP_VALIDATION_REQUEST',
    OTP_VALIDATION_SUCCESS: 'OTP_VALIDATION_SUCCESS',
    OTP_VALIDATION_FAILURE: 'OTP_VALIDATION_FAILURE',

    RESET_PASSWORD_REQUEST: 'RESET_PASSWORD_REQUEST',
    RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS',
    RESET_PASSWORD_FAILURE: 'RESET_PASSWORD_FAILURE',
    RESET_PASSWORD_ALERT_DISMISS: 'RESET_PASSWORD_ALERT_DISMISS'
};