export const cashConstants = {
    SUM_AMOUNT: 'SUM_AMOUNT',
    SUM_TOTAL: 'SUM_TOTAL',
    BACK_AMOUNT:'BACK_AMOUNT',
    CLEAR_AMOUNT:'CLEAR_AMOUNT',
    CHANGE_OPTION:'CHANGE_OPTION',
    ADD_DISCOUNT:'ADD_DISCOUNT',
    ADD_DELIVERY:'ADD_DELIVERY',
    REMOVE_DISCOUNT: 'REMOVE_DISCOUNT',
    REMOVE_DELIVERY: 'REMOVE_DELIVERY',
};